import { deal1, deal2, deal3, deal4, deal5, deal6 } from '@/shared/assets';

export const bestDeals = [
    {
        id: 1,
        image: deal1,
        title: 'Best Burgers',
        type: 'Burgers',
        address: '42 Jong Panchester St, 9073',
        time: '20-30 min',
        score: '9.8',
        price: 'From $4',
    },
    {
        id: 2,
        image: deal2,
        title: 'Pizza Masters',
        type: 'Pizza',
        address: 'Ac St. Schaumburg 84872',
        time: '~45 min',
        price: 'From $4',
        score: '9.8',
    },
    {
        id: 3,
        image: deal3,
        title: 'Luxury Restaurant',
        type: 'Asian',
        address: 'Kennewick AL 41329',
        time: '15-20 min',
        price: 'From $4',
        score: '7.3',
    },
    {
        id: 4,
        image: deal4,
        title: 'Italian Cuisine',
        type: 'Sushi',
        address: '8019 Facilisis Street',
        time: '30-40 min',
        price: 'From $4',
        score: '8.0',
    },
    {
        id: 5,
        image: deal5,
        title: 'Elegant Cafe',
        type: 'Bakery',
        address: '8441 Eleifend Street',
        time: '~20 min',
        price: 'From $4',
        score: '9.8',
    },
    {
        id: 6,
        image: deal6,
        title: 'Cafe & Bakery',
        type: 'Pizza',
        address: '9631 Semper Ave Astoria',
        time: '10-20 min',
        price: 'From $4',
        score: '9.8',
    },
];
